services:
  device_dev_postgres_container:
    image: postgres:17-alpine
    container_name: device_api_dev_postgres_container
    environment:
      POSTGRES_DB: device_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data-dev:/var/lib/postgresql/data

volumes:
  postgres-data-dev:
