services:
  device_postgres_container:
    image: postgres:17-alpine
    container_name: device_api_postgres_container
    environment:
      POSTGRES_DB: device_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - custom_bridge_network

  app:
    build: .
    container_name: device-api-service
    ports:
      - "8080:8080"
    depends_on:
      - device_postgres_container
    environment:
      DB_HOST: jdbc:postgresql://device_api_postgres_container:5432/device_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - custom_bridge_network

volumes:
  postgres-data:

networks:
  custom_bridge_network:
    name: "custom_bridge_network"
    driver: bridge